# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#TODO rename the file
name: Test, Documentation and Build Photonomist

on:
  push:
    branches: [ gui, master, documentation ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py build && python setup.py install
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Install Tkinter -- libtk8.6.so: cannot open shared object file
      run: |
        sudo pacman -S tk
        sudo apt-get install tk
 
    #- uses: actions/checkout@v1
    - name: Build Documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: doc/
    
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: doc/_build/html/

    # - name: Test with pytest
    #   run: |
    #     pytest

    # - name: Package Application
    #   uses: JackMcKew/pyinstaller-action-windows@main
    #   with:
    #     path: src/GUI

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: photonomist
    #     path: src/GUI/dist/windows

