# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test, Documentation and Build Photonomist

on:
  push:
    branches: [ gui ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest

    # - name: Build Graphical User Interface
    #   uses: JackMcKew/pyinstaller-action-windows@main
    #   with:
    #     path: src/GUI

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: photonomist
    #     path: src/dist/gui_folder
    - name: Build photonomist.exe
      run: |
        pyinstaller --noconsole --onefile /home/runner/work/photonomist/photonomist/src/GUI/main.py
    - name: Upload photonomist.exe into dist
        uses: actions/upload-artifact@v2
        with:
          name: dir for photonomist.exe
          path: |
            dist
